language: minimal

services:
  - docker

before_script:
  - ./build

script:
  - for image in alpine qa 10-alpine 8-alpine; do
      docker run -it fireworkweb/node:$DOCKER_IMAGE node -v
      docker run -it fireworkweb/node:$DOCKER_IMAGE npm -v
      docker run -it fireworkweb/node:$DOCKER_IMAGE yarn -v
    done
