language: minimal

services:
  - docker

before_script:
  - ./build.sh

script:
  - for image in alpine qa 10-alpine 8-alpine; do
      docker run -it fireworkweb/node:$image node -v;
      docker run -it fireworkweb/node:$image npm -v;
      docker run -it fireworkweb/node:$image yarn -v;
    done
