name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, qa, 14, 14-qa, 12, 12-qa, 10, 10-qa, 8, 8-qa]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build docker images
      run: |
        docker build --pull -t fireworkweb/node:${{ matrix.version }} ${{ matrix.version }}

    - name: Test docker images
      run: |
        docker run fireworkweb/node:${{ matrix.version }} node -v;
        docker run fireworkweb/node:${{ matrix.version }} npm -v;
        docker run fireworkweb/node:${{ matrix.version }} yarn -v;

        docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }} node -v;
        docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }} npm -v;
        docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }} yarn -v;

    - name: Push to Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fireworkweb/node:${{ matrix.version }}
