name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build docker image base
      run: |
        docker build --pull -t fireworkweb/node:${{ matrix.version }} ${{ matrix.version }}

    - name: Build docker image adonis
      run: |
        docker build -t fireworkweb/node:${{ matrix.version }}-adonis ${{ matrix.version }}-adonis

    - name: Build docker image adonis-qa
      run: |
        docker build -t fireworkweb/node:${{ matrix.version }}-adonis-qa ${{ matrix.version }}-adonis-qa

    - name: Build docker image qa
      run: |
        docker build -t fireworkweb/node:${{ matrix.version }}-qa ${{ matrix.version }}-qa

    - name: Tag image latest
      if: matrix.version == '14'
      run: |
        docker tag fireworkweb/node:${{ matrix.version }} fireworkweb/node:latest

    - name: Tag image adonis
      if: matrix.version == '14'
      run: |
        docker tag fireworkweb/node:${{ matrix.version }}-adonis fireworkweb/node:adonis

    - name: Tag image adonis-qa
      if: matrix.version == '14'
      run: |
        docker tag fireworkweb/node:${{ matrix.version }}-adonis-qa fireworkweb/node:adonis-qa

    - name: Tag image qa
      if: matrix.version == '14'
      run: |
        docker tag fireworkweb/node:${{ matrix.version }}-qa fireworkweb/node:qa

    - name: Test docker images
      run: |
        for suffix in '' -adonis -adonis-qa -qa; do
          docker run fireworkweb/node:${{ matrix.version }}$suffix node -v;
          docker run fireworkweb/node:${{ matrix.version }}$suffix npm -v;
          docker run fireworkweb/node:${{ matrix.version }}$suffix yarn -v;

          docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }}$suffix node -v;
          docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }}$suffix npm -v;
          docker run -e ASUSER=1000 fireworkweb/node:${{ matrix.version }}$suffix yarn -v;
        done

    - name: Push to hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        docker push fireworkweb/node:${{ matrix.version }}
        docker push fireworkweb/node:${{ matrix.version }}-adonis
        docker push fireworkweb/node:${{ matrix.version }}-adonis-qa
        docker push fireworkweb/node:${{ matrix.version }}-qa

    - name: Push to hub latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.version == '14'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        docker push fireworkweb/node:latest
        docker push fireworkweb/node:adonis
        docker push fireworkweb/node:adonis-qa
        docker push fireworkweb/node:qa
